// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// import 'firebase_options.dart';
// / // ...
// await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
// );

/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZXQDQEUwGyi5Jqiiswo8Igp04hyauqxU',
    appId: '1:1024292233306:web:1109404855ab27cc1a7863',
    messagingSenderId: '1024292233306',
    projectId: 'sparcs-hackathon',
    authDomain: 'sparcs-hackathon.firebaseapp.com',
    storageBucket: 'sparcs-hackathon.appspot.com',
    measurementId: 'G-8CSS8P7ZSP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv_5aP073c-c9UiSlgs8Uh4md0RQpBiCQ',
    appId: '1:1024292233306:android:35ac97e40c37ebc71a7863',
    messagingSenderId: '1024292233306',
    projectId: 'sparcs-hackathon',
    storageBucket: 'sparcs-hackathon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApTgsoWcFKSZ_0_7R5Z_jl4SzV6vCvbEY',
    appId: '1:1024292233306:ios:109a8cfe6a5ff55d1a7863',
    messagingSenderId: '1024292233306',
    projectId: 'sparcs-hackathon',
    storageBucket: 'sparcs-hackathon.appspot.com',
    iosClientId:
        '1024292233306-u60h9ei88knkf51irkd32qitaukr2bg7.apps.googleusercontent.com',
    iosBundleId: 'com.example.netgalpi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApTgsoWcFKSZ_0_7R5Z_jl4SzV6vCvbEY',
    appId: '1:1024292233306:ios:e959c059352ca6ad1a7863',
    messagingSenderId: '1024292233306',
    projectId: 'sparcs-hackathon',
    storageBucket: 'sparcs-hackathon.appspot.com',
    iosClientId:
        '1024292233306-odnmraujj7g2o3l3vqpc4m657lvnrpbv.apps.googleusercontent.com',
    iosBundleId: 'com.example.netgalpi.RunnerTests',
  );
}
